version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: fintrack-mongodb
    environment:
      MONGO_INITDB_DATABASE: dev_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: fintrack-postgres
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: fintrack-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: fintrack-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  # Spring Boot Backend
  backend:
    image: eclipse-temurin:21-jdk-alpine
    container_name: fintrack-backend
    depends_on:
      - postgres
      - mongodb
      - kafka
    volumes:
      - ./target:/app
    working_dir: /app
    command: ["java", "-jar", "backend-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dev_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@mongodb:27017/dev_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  # PostgreSQL Exporter
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: fintrack-postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:root@postgres:5432/dev_db?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  # Kafka Exporter
  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: fintrack-kafka-exporter
    command: ["--kafka.server=kafka:9092"]
    ports:
      - "9308:9308"
    depends_on:
      - kafka

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: fintrack-prometheus
    volumes:
      - ./monitoring:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - postgres-exporter
      - kafka-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: fintrack-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_DASHBOARDS_JSON_PATH=/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  mongo_data:
  postgres_data:
  grafana_data:
