create table test(
    id serial primary key
    name text,
    username text
);

--DATABASE MVP--
--
---- =======================================
---- 1️⃣ users table
---- Stores core authentication, identity, and profile data
---- =======================================
--create table users (
--                       id bigserial primary key,
--
--    -- authentication / identity
--                       username varchar(50) unique not null,
--                       email varchar(100) unique not null,
--                       email_verified boolean default false,
--                       phone_number varchar(20),
--                       phone_verified boolean default false,
--                       password_hash text not null,
--
--    -- profile data
--                       first_name varchar(100) not null,
--                       last_name varchar(100) not null,
--                       sir_name varchar(100),
--                       date_of_birth date,
--                       gender varchar(50),
--                       country varchar(100),
--                       city varchar(100),
--                       occupation varchar(100),
--                       income_bracket varchar(50),
--                       preferred_currency char(3) default 'usd',
--
--                       created_at timestamp default now(),
--                       updated_at timestamp default now()
--);
--
---- =======================================
---- 2️⃣ sessions table
---- Tracks user sessions and environment details
---- =======================================
--create table sessions (
--                          id bigserial primary key,
--                          user_id bigint references users(id) on delete cascade,
--
--    -- session lifecycle
--                          session_start timestamp default now(),
--                          session_end timestamp,
--                          is_active boolean default true,
--
--    -- device environment
--                          device_type varchar(50),
--                          device_model varchar(100),
--                          os_version varchar(50),
--                          app_version varchar(50),
--
--    -- network and location
--                          ip_address varchar(50),
--                          network_type varchar(100),
--                          location varchar(255),
--
--    -- session metrics
--                          actions_count int default 0,
--                          transactions_count int default 0,
--                          avg_screen_time numeric(10,2),
--                          crash_reports jsonb
--);
--
---- indexes for faster queries
--create index idx_sessions_user on sessions(user_id);
--create index idx_sessions_device on sessions(device_type, device_model);
--create index idx_sessions_location on sessions(location);
--create index idx_sessions_time on sessions(session_start);
--
---- =======================================
---- 3️⃣ session_events table
---- Stores micro-level events inside a session
---- =======================================
--create table session_events (
--                                event_id bigserial primary key,
--                                session_id bigint not null references sessions(id) on delete cascade,
--                                user_id bigint not null references users(id) on delete cascade,
--
--                                event_type varchar(100) not null, -- login, add_transaction, view_market, crash
--                                event_data jsonb,
--                                event_time timestamp default current_timestamp
--);
--
---- indexes for analytics
--create index idx_event_type on session_events(event_type);
--create index idx_event_time on session_events(event_time);
--
---- =======================================
---- 4️⃣ session_factors table
---- External/internal factors affecting a session
---- =======================================
--create table session_factors (
--                                 factor_id bigserial primary key,
--                                 session_id bigint references sessions(id) on delete cascade,
--                                 user_id bigint not null references users(id) on delete cascade,
--
--                                 factor_type varchar(100) not null, -- network_issue, market_event, device_battery, peak_hours
--                                 factor_value varchar(255),
--                                 factor_score numeric(5,2),
--                                 recorded_at timestamp default current_timestamp
--);
--
--create index idx_factor_type on session_factors(factor_type);
--
---- =======================================
---- 5️⃣ accounts table
---- User financial accounts
---- =======================================
--create type account_type as enum('cash', 'bank', 'credit', 'investment');
--
--create table accounts (
--                          id bigserial primary key,
--                          user_id bigint references users(id) on delete cascade,
--
--    -- core account details
--                          name varchar(100) not null,
--                          type account_type not null,
--                          currency varchar(10) not null,
--                          provider varchar(100),
--
--    -- financial values
--                          balance numeric(20,2) default 0,
--                          available_balance numeric(20,2) default 0,
--                          total_inflow numeric(20,2) default 0,
--                          total_outflow numeric(20,2) default 0,
--                          num_transactions int default 0,
--
--    -- timestamps
--                          account_created_at timestamp default now(),
--                          account_updated_at timestamp default now(),
--                          closed_at timestamp,
--                          last_synced timestamp
--);
--
--create index idx_accounts_user on accounts(user_id);
--create index idx_accounts_type on accounts(type);
--create index idx_accounts_provider on accounts(provider);
--create index idx_accounts_currency on accounts(currency);
--
---- =======================================
---- 6️⃣ transactions table
---- Financial transactions per account
---- =======================================
--create type transaction_type as enum('income', 'expense', 'transfer');
--
--create table transactions (
--                              id bigserial primary key,
--                              account_id bigint references accounts(id) on delete cascade,
--
--                              type transaction_type not null,
--                              category varchar(100),
--                              amount numeric(20,2) not null,
--                              location varchar(255),
--                              merchant varchar(255),
--                              description text,
--                              payment_method varchar(50),
--                              recurring boolean default false,
--                              tag text,
--                              transaction_date timestamp default now()
--);
--
--create index idx_transactions_account on transactions(account_id);
--create index idx_transactions_category on transactions(category);
--
---- =======================================
---- 7️⃣ categories table
---- Transaction categories for classification
---- =======================================
--create table categories (
--                            id serial primary key,
--                            name varchar(100) not null,
--                            type transaction_type not null,
--                            total_transactions int default 0,
--                            total_amount numeric(20,2) default 0
--);
--
---- =======================================
---- 8️⃣ budgets table
---- User budgets across categories
---- =======================================
--create type budget_period as enum('daily','weekly','monthly','yearly');
--
--create table budgets (
--                         id serial primary key,
--                         user_id bigint references users(id) on delete cascade,
--
--                         name varchar(255) not null,
--                         amount numeric(20,2) not null,
--                         period budget_period default 'monthly',
--                         category varchar(100),
--                         start_date timestamp default now(),
--                         end_date timestamp,
--                         spend_amount numeric(20,2) default 0,
--                         remaining_balance numeric(20,2) default 0,
--                         budget_status boolean default true
--);
--
--create index idx_budgets_user on budgets(user_id);
--
---- =======================================
---- 9️⃣ goals table
---- User financial goals
---- =======================================
--create table goals (
--                       id serial primary key,
--                       user_id bigint references users(id) on delete cascade,
--
--                       name varchar(255) not null,
--                       target_amount numeric(20,2) not null,
--                       current_amount numeric(20,2) default 0,
--                       progress_percentage numeric(5,2) default 0,
--                       num_contributions int default 0,
--
--                       created_at timestamp default now(),
--                       due_date timestamp
--);
--
--create index idx_goals_user on goals(user_id);
--
---- =======================================
---- 🔟 market_assets table
---- Assets for markets (stock, crypto, forex)
---- =======================================
--create type asset_type as enum('stock','crypto','forex');
--
--create table market_assets (
--                               id serial primary key,
--                               symbol varchar(50) not null,
--                               name varchar(255) not null,
--                               type asset_type not null,
--                               currency varchar(10) not null
--);
--
---- =======================================
---- 11️⃣ user_portfolio table
---- User holdings in market assets
---- =======================================
--create table user_portfolio (
--                                id serial primary key,
--                                user_id bigint references users(id) on delete cascade,
--                                asset_id int references market_assets(id) on delete cascade,
--
--                                quantity numeric(20,6) default 0,
--                                avg_price numeric(20,2) default 0,
--                                current_price numeric(20,2) default 0,
--                                last_updated timestamp default now()
--);
--
--create index idx_portfolio_user_asset on user_portfolio(user_id, asset_id);
--
---- =======================================
---- 12️⃣ market_prices table
---- Price history for assets
---- =======================================
--create table market_prices (
--                               id serial primary key,
--                               asset_id int references market_assets(id) on delete cascade,
--                               price numeric(20,2) not null,
--                               recorded_at timestamp default now()
--);
--
--create index idx_market_prices_asset on market_prices(asset_id);
--
---- =======================================
---- 13️⃣ reports table
---- System-generated user reports
---- =======================================
--create type report_type as enum(
--    'expense_summary','income_summary','budget_progress',
--    'goal_progress','investment_portfolio','market_tracking'
--);
--
--create table reports (
--                         id serial primary key,
--                         user_id bigint references users(id) on delete cascade,
--
--                         type report_type not null,
--                         data_json jsonb not null,
--                         generated_at timestamp default now()
--);
